### ISSUE TITLE
Test session analysis CSV truncates lap times 1 hour or longer

### ISSUE THREAD

**Issue by motomatters** [fabricepipart/mgp-timings#140]
The PDF parser for the Analysis PDFs misinterprets lap times 1 hour or longer (technically, longer than 59'59.999). 

All lap times longer than 1 hour are truncated and skipped from the CSV.

To reproduce:
https://mgp-timings.teknichrono.fr/session/test/2023/MY2/motogp/FP3/analysis/csv

It's arguable whether this is a significant issue, as it doesn't make any difference to the outcome. But it can be useful when reconstructing timings of the test (e.g. when particular riders set their times).

**Comment by fabricepipart** [comment]
Perfect feedback. No arguing that is something to fix :)
I'll do that hopefully by the end of the week.
Thanks for your interest

**Comment by fabricepipart** [comment]
Fix was easy ;)

**Comment by fabricepipart** [comment]
Seems fine now !
