### ISSUE TITLE
MotoGP API change has bolloxed everything up - Error codes being returned

### ISSUE THREAD

**Issue by motomatters** [fabricepipart/mgp-timings#183]
Looks like the change to the new website has messed up the application. The only thing that gets returned is an error ID code.

500 Server Error 
{
  "details": "Error id 4283d464-2a87-4322-9982-3c582c52ee3f-5",
  "stack": ""
}

**Comment by fabricepipart** [comment]
I need to find the time to work on it ASAP

**Comment by motomatters** [comment]
If it's any consolation, the new MotoGP.com website has made everyone's job about a million times harder, as so much data is missing now.

**Comment by fabricepipart** [comment]
Sorry I did not progress yet... I am off for 2 more weeks and focus on ... disconnecting for now ;-)

**Comment by fabricepipart** [comment]
I gave it a first try today (1h or so). Thanks to the work a common Twitter friend provided, this seems perfectly feasible to adapt everything. Devil will be in the details but for now I am rather confident.

Unfortunately, I start a motorcycle trip in the next days. It's unlikely I ll be able to finish before that.

**Comment by fabricepipart** [comment]
I currently have 102 tests over 149 that pass

**Comment by fabricepipart** [comment]
123 / 149 ;)

**Comment by fabricepipart** [comment]
126 / 149

**Comment by fabricepipart** [comment]
I only did some very basic tests. But it seems to be working again !
